hustcc/jest-canvas-mock

__tests__/index.js, lib/window.js, package-lock.json, src/window.js
Hi!
I work with the [openlayers](http://openlayers.org/) library, which internally create a canvas with `document.createElement("CANVAS")`, and that would not work with **jest-canvas-mock**, as it checks the parameter with `param === 'canvas'`.
Since the [createElement API](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) allows passing the element name with any casing (it will convert to lowercase), I've updated the mock to check the parameter with `param.toString().toLowerCase() === 'canvas'`.
This solved my particular case, and may be useful to others.
Thanks!
=> Handle calling createElement passing "canvas" with different casing.

__tests__/server-side.js, lib/index.js, src/index.js
Fixes #6
Allows `jest-canvas-mock` to run normally in jsdom environments.
Allows the mocking to fail silently in node environments, which is needed to test components that are rendered both on the client and on the server.
=> fix(ssr): allow mocking to fail silently in node env

__tests__/index.js, src/classes/context2d.js
This PR adds handling of parameters to `createImageData()` and returns the correctly-shaped object.
=> Add createImageData() implementation

__tests__/classes/CanvasRenderingContext2D.fillStyle.js, __tests__/classes/CanvasRenderingContext2D.shadowColor.js, __tests__/classes/CanvasRenderingContext2D.strokeStyle.js, src/classes/CanvasRenderingContext2D.js, src/mock/createImageBitmap.js
Developers who want to actually mock their fetch calls using the `jest-fetch-mock` package will run into problems with `createImageBitmap`. Calling `response.toBlob()` will return a `Blob`-like object, however the fetch implementation is not aware of the environment's `Blob` constructor.
Lastly, I don't have faith that https://github.com/jefflau/jest-fetch-mock/issues/105 will yield something helpful.
This pull request contains a small fixes that assume `jest-fetch-mock` won't fall through. Instead we should do duck typing.
Since it's possible to inspect the `blob.constructor.name` property, we can do this:
```ts
if (img instanceof Blob || (img && img.constructor && img.constructor.name === "Blob")) validImage = true;
```
I think these changes are safe. and likely will not provide false …
=> [RFC] External Blob Support

__tests__/mock/prototype.js, src/mock/prototype.js
This pull request maintains 100% code coverage, fixes standard `HTMLCanvasElement#getContext` behavior.
closes #34
=> fix(getcontext): repeated calls to getContext('2d') return same context

package.json
I'd like to add a "prepare" script so that I can install the module from a github URL.
=> feat(build): add prepare script

README.md
add a section in the README on how to override the default mock return value
=> docs(mock): add doc on how to override mock return value

.gitignore, __tests__/classes/ImageData.js, src/classes/ImageData.js
This PR introduces changes in the `ImageData` class to comply with the [official specification](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-createimagedata).
- `ImageData()` now supports instantiation using the syntax: `new ImageData(array, width [, height]);`.
- More semantic error types.
- Test suite for the class was refactored, each inner `describe` block corresponds to each valid way to instantiate `ImageData`. All tests from the previous version are in the first inner `describe` block.
=> Support for ImageData instantiation using a source array

__tests__/classes/CanvasRenderingContext2D.__getDrawCalls.js, __tests__/classes/CanvasRenderingContext2D.__getEvents.js, __tests__/classes/CanvasRenderingContext2D.__getPath.js, src/classes/CanvasRenderingContext2D.js
The `__get*` methods on the CanvasRenderingContext2D class currently take an unnecessary `ctx` argument. This is inconsistent with both the README and the TypeScript interface's documentation of these methods. This change removes the argument and updates the tests to match.
=> fix(context): :anchor: Removes argument to getters

README.md, __tests__/classes/CanvasRenderingContext2D.__clearDrawCalls.js, __tests__/classes/CanvasRenderingContext2D.__clearEvents.js, __tests__/classes/CanvasRenderingContext2D.__clearPath.js, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__clearDrawCalls.js.snap, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__clearEvents.js.snap, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__clearPath.js.snap, package.json, src/classes/CanvasRenderingContext2D.js, types/index.d.ts
* Adds __clearDrawCalls for clearing draw calls
* Adds __clearEvents for clearing events
* Updates README to mention the new functions
* Adds TypeScript definitions for __clearDrawCalls and __clearEvents
Closes #48.
I decided not to add `__clearPath` as that is cleared for every `beginPath` call already.
I have never used TypeScript, so the definitions are a bit of a guess.
=> feat(mock): support clearing draw calls and events

.babelrc, .travis.yml, CHANGELOG.md, __tests__/classes/CanvasRenderingContext2D.lineWidth.js, package.json, src/classes/CanvasRenderingContext2D.js
Apparently I don't have write access to the repo, but that's fine. I can submit pull requests like this.
Changes:
- Add support for node 13
- remove support for node 6 and 7
- add slice to transform push (adds more memory usage but is compliant with spec
- update babel env to target node 8
- update node packages
- cleanup changelog docs
Please check my work and publish at your convenience.
I didn't include the version bump to 2.2.0, but you should definitely do this when you're ready.
Fixes: #50 
Fixes: #53
=> fix(transform): slice transform on save, node 13

README.md, __tests__/classes/CanvasRenderingContext2D.__getClippingPath.js, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__getClippingPath.js.snap, package.json, src/classes/CanvasRenderingContext2D.js, types/index.d.ts
fixes #54 
Not sure if the tests are conclusive enough, but I am pretty sure this covers the niche need for testing clipping regions.
=> feat(clip): add clippath

CHANGELOG.md, README.md, __tests__/classes/CanvasGradient.js, __tests__/classes/CanvasRenderingContext2D.fillStyle.js, __tests__/classes/CanvasRenderingContext2D.shadowColor.js, __tests__/classes/CanvasRenderingContext2D.strokeStyle.js, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__getEvents.js.snap, package.json, src/classes/CanvasGradient.js, src/classes/CanvasRenderingContext2D.js
No other modules I found could be used _plug'n'play_ here. It seems that the only value that parse-color doesn't handle correctly is `transparent`, so it can be handled especially
Some test cases that verify different color formats get handled correctly wouldn't hurt either.
resolves #64
=> fix(gradients): support for 'transparent' as a color stop

__tests__/classes/DOMMatrix.js, src/classes/DOMMatrix.js
Add 2 methods that DOMMatrix has but is missing in the mock
- `toFloat32Array()`
- `toFloat64Array()`
=> feat(DOMMatrix): add toFloat32Array and toFloat64Array

README.md, __tests__/classes/CanvasRenderingContext2D.__getClippingPath.js, __tests__/classes/CanvasRenderingContext2D.restore.js, __tests__/classes/__snapshots__/CanvasRenderingContext2D.__getClippingPath.js.snap, src/classes/CanvasRenderingContext2D.js
Previously, the restore() method would update its pointer to the previous clipping region (stackIndex = n-1) in the stack without deleting the current clipping region (stackIndex = n). This caused problems for future save() calls, which would push a new clipping region onto the stack at location n+1 while only incrementing stackIndex to n, thus referencing the wrong region.
This commit fixes the issue by deleting the current clipping region when restore() is called. By doing this, we lose the ability to inspect old clipping regions, but this is easy to change in the future if it is desired.
=> Fix(clip): delete clipping region with restore

__tests__/classes/__snapshots__/CanvasRenderingContext2D.__getEvents.js.snap, src/classes/CanvasRenderingContext2D.js
use the same parameter name as in `typescript/lib/lib.dom.d.ts`
```ts
interface CanvasPathDrawingStyles {
// ....
setLineDash(segments: number[]): void;
}
```
so we can auto-generate interfaces as shown [here](https://github.com/MrMaxie/ts-types-parser/pull/4)
=> fix setLineDash parameter name: value -> segments

.github/workflows/build.yml, .travis.yml, README.md, __mocks__/worker.js, package.json, src/index.js
- Fix #89, also closes #84
- Move to GitHub Actions (related to #90)
=> fix(window): avoid `global.window` redefinition

.gitignore, README.md, __tests__/index.js, src/index.js, types/index.d.ts
This allows consumers of this library to use the mock with `jest.resetAllMocks()`
Should allow workarounds for https://github.com/hustcc/jest-canvas-mock/issues/72
=> index: export a function to re-initialize mocks

CHANGELOG.md, __tests__/vis.js, package.json
- feat: export a function to re-initialize mocks (#98)
- docs: fix some typos (#104)
- fix: copy & paste mistake: toBlob -> toDataURL (#101)
- chore: add Contributors LitoMore (#94)
=> chore: v2.5.0

README.md, __tests__/classes/CanvasRenderingContext2D.getImageData.js, __tests__/vis.js, src/classes/CanvasRenderingContext2D.js
fixes #110
- check parameter count for `CanvasRenderingContext2d#getImageData`
- use width/height parameter for resulting `ImageData`
- adapt unit test
=> #110: parameter support for getImageData

README.md, types/index.d.ts
Currently, setupJestCanvasMock is typed using `{}`, however this causes a TypeScript error, TS1183: An implementation cannot be declared in ambient contexts.
Instead, use `void` as the return type to fix this error
This should fix #107
=> Fix setupJestCanvasMock type declaration

__tests__/mock/window.js, src/mock/prototype.js, src/window.js
When mocking the canvas on a non-global window object, the prototype
mocks should apply to the same window object.
=> Pass window object to mockPrototype

__tests__/mock/prototype.js, __tests__/mock/window.js, package.json, src/mock/prototype.js
=> fix(jest-canvas-mock): account for possible `TypeError`
